name: Publish Wheels

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-wheels.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  publish_wheels:
    name: Publish Wheels to PyPI
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyraymesh
    permissions:
      id-token: write

    steps:

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish wheels
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
  #          password: ${{ secrets.TEST_PYPI_TOKEN }}
  #          repository-url: https://test.pypi.org/legacy/
  #          verbose: true